<#
.SYNOPSIS
    Packs the Chrome extension as a CRX2 file and outputs the extension ID.
    Called by Jenkinsfile — expects the private key path as an argument.

.PARAMETER ExtensionDir
    Path to the folder containing the unpacked extension files.

.PARAMETER KeyFile
    Path to the PEM private key (PKCS#8) generated by generate-extension-key.ps1.

.PARAMETER OutputCrx
    Destination path for the packed .crx file.

.PARAMETER OutputIdFile
    Path to write the computed extension ID (one line, for use in InnoSetup).

.EXAMPLE
    .\pack-extension.ps1 -ExtensionDir ..\extension -KeyFile key.pem `
                         -OutputCrx court-meta.crx -OutputIdFile extension-id.txt
#>
param(
    [Parameter(Mandatory)][string]$ExtensionDir,
    [Parameter(Mandatory)][string]$KeyFile,
    [Parameter(Mandatory)][string]$OutputCrx,
    [Parameter(Mandatory)][string]$OutputIdFile
)

$ErrorActionPreference = "Stop"

# ── Load RSA private key ──────────────────────────────────────────────────────
$pemContent = Get-Content $KeyFile -Raw
$rsa = [System.Security.Cryptography.RSA]::Create()
$rsa.ImportFromPem($pemContent)

# ── Zip the extension directory ───────────────────────────────────────────────
$zipTemp = [System.IO.Path]::GetTempFileName() + ".zip"
Compress-Archive -Path "$ExtensionDir\*" -DestinationPath $zipTemp -Force
$zipBytes = [System.IO.File]::ReadAllBytes($zipTemp)
Remove-Item $zipTemp -Force

# ── Build CRX2 binary ─────────────────────────────────────────────────────────
# Format: magic(4) | version(4 LE) | pubKeyLen(4 LE) | sigLen(4 LE) | pubKey | sig | zip
$spki      = $rsa.ExportSubjectPublicKeyInfo()
$signature = $rsa.SignData($zipBytes,
                           [System.Security.Cryptography.HashAlgorithmName]::SHA1,
                           [System.Security.Cryptography.RSASignaturePadding]::Pkcs1)

$ms = [System.IO.MemoryStream]::new()
$ms.Write([System.Text.Encoding]::ASCII.GetBytes("Cr24"), 0, 4)
$ms.Write([BitConverter]::GetBytes([uint32]2), 0, 4)
$ms.Write([BitConverter]::GetBytes([uint32]$spki.Length), 0, 4)
$ms.Write([BitConverter]::GetBytes([uint32]$signature.Length), 0, 4)
$ms.Write($spki, 0, $spki.Length)
$ms.Write($signature, 0, $signature.Length)
$ms.Write($zipBytes, 0, $zipBytes.Length)

[System.IO.File]::WriteAllBytes($OutputCrx, $ms.ToArray())
$ms.Dispose()
Write-Host "CRX written: $OutputCrx ($([Math]::Round($ms.Length/1KB, 1)) KB)"

# ── Compute extension ID ──────────────────────────────────────────────────────
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$hash   = $sha256.ComputeHash($spki)
$extId  = -join ($hash[0..15] | ForEach-Object {
    [char]([byte][char]'a' + (($_ -shr 4) -band 0x0F))
    [char]([byte][char]'a' + ($_ -band 0x0F))
})

Set-Content -Path $OutputIdFile -Value $extId -Encoding UTF8 -NoNewline
Write-Host "Extension ID: $extId"
